// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EngagementLevel struct {
	Type    []*string `json:"type,omitempty"`
	Details *string   `json:"details,omitempty"`
}

type EngagementLevelInput struct {
	Type    []*string `json:"type,omitempty"`
	Details *string   `json:"details,omitempty"`
}

type InvestmentRange struct {
	FromUsd *int32 `json:"from_usd,omitempty"`
	ToUsd   *int32 `json:"to_usd,omitempty"`
}

type InvestmentRangeAndFee struct {
	InvestmentRange       *InvestmentRange `json:"investment_range,omitempty"`
	AdvisoryFeeUsdPerHour *int32           `json:"advisory_fee_usd_per_hour,omitempty"`
}

type InvestmentRangeAndFeeInput struct {
	InvestmentRange       *InvestmentRangeInput `json:"investment_range,omitempty"`
	AdvisoryFeeUsdPerHour *int32                `json:"advisory_fee_usd_per_hour,omitempty"`
}

type InvestmentRangeInput struct {
	FromUsd *int32 `json:"from_usd,omitempty"`
	ToUsd   *int32 `json:"to_usd,omitempty"`
}

type InvestorProfile struct {
	RoleFocus                  *RoleFocus             `json:"role_focus,omitempty"`
	IndustryExpertise          []*string              `json:"industry_expertise,omitempty"`
	GeographicPreference       []*string              `json:"geographic_preference,omitempty"`
	InvestmentAdvisoryStage    []*string              `json:"investment_advisory_stage,omitempty"`
	InvestmentRangeAdvisoryFee *InvestmentRangeAndFee `json:"investment_range_advisory_fee,omitempty"`
	DealStructurePreferences   []*string              `json:"deal_structure_preferences,omitempty"`
	EngagementLevel            *EngagementLevel       `json:"engagement_level,omitempty"`
	KeyStrengths               []*string              `json:"key_strengths,omitempty"`
	NetworkAndValueAdd         *NetworkValueAdd       `json:"network_and_value_add,omitempty"`
	SuccessMetrics             []*string              `json:"success_metrics,omitempty"`
}

type InvestorProfileInput struct {
	RoleFocus                  *RoleFocusInput             `json:"role_focus,omitempty"`
	IndustryExpertise          []*string                   `json:"industry_expertise,omitempty"`
	GeographicPreference       []*string                   `json:"geographic_preference,omitempty"`
	InvestmentAdvisoryStage    []*string                   `json:"investment_advisory_stage,omitempty"`
	InvestmentRangeAdvisoryFee *InvestmentRangeAndFeeInput `json:"investment_range_advisory_fee,omitempty"`
	DealStructurePreferences   []*string                   `json:"deal_structure_preferences,omitempty"`
	EngagementLevel            *EngagementLevelInput       `json:"engagement_level,omitempty"`
	KeyStrengths               []*string                   `json:"key_strengths,omitempty"`
	NetworkAndValueAdd         *NetworkValueAddInput       `json:"network_and_value_add,omitempty"`
	SuccessMetrics             []*string                   `json:"success_metrics,omitempty"`
}

type Mutation struct {
}

type NetworkValueAdd struct {
	Network           *string `json:"network,omitempty"`
	AdditionalSupport *string `json:"additional_support,omitempty"`
}

type NetworkValueAddInput struct {
	Network           *string `json:"network,omitempty"`
	AdditionalSupport *string `json:"additional_support,omitempty"`
}

type NewUser struct {
	FullName        string                `json:"full_name"`
	Email           string                `json:"email"`
	InvestorProfile *InvestorProfileInput `json:"investor_profile,omitempty"`
}

type Query struct {
}

type RoleFocus struct {
	Role       []*string `json:"role,omitempty"`
	FocusAreas []*string `json:"focus_areas,omitempty"`
}

type RoleFocusInput struct {
	Role       []*string `json:"role,omitempty"`
	FocusAreas []*string `json:"focus_areas,omitempty"`
}

type User struct {
	ID              string           `json:"id"`
	FullName        string           `json:"full_name"`
	Email           string           `json:"email"`
	InvestorProfile *InvestorProfile `json:"investor_profile,omitempty"`
}
